/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConvidadoRouteImport } from './routes/convidado'
import { Route as ConvidadoDiarioRouteImport } from './routes/convidado-diario'
import { Route as ConvidadoMedicamentosRouteImport } from './routes/convidado-medicamentos'
import { Route as ConvidadoNotificacoesRouteImport } from './routes/convidado-notificacoes'
import { Route as ConviteRouteImport } from './routes/convite'
import { Route as AuthenticatedConversarRouteImport } from './routes/_authenticated/conversar'
import { Route as AuthenticatedDiarioRouteImport } from './routes/_authenticated/diario'
import { Route as AuthenticatedHojeRouteImport } from './routes/_authenticated/hoje'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedRemediosRouteImport } from './routes/_authenticated/remedios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvidadoRoute = ConvidadoRouteImport.update({
  id: '/convidado',
  path: '/convidado',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvidadoDiarioRoute = ConvidadoDiarioRouteImport.update({
  id: '/convidado-diario',
  path: '/convidado-diario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvidadoMedicamentosRoute = ConvidadoMedicamentosRouteImport.update({
  id: '/convidado-medicamentos',
  path: '/convidado-medicamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvidadoNotificacoesRoute = ConvidadoNotificacoesRouteImport.update({
  id: '/convidado-notificacoes',
  path: '/convidado-notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteRoute = ConviteRouteImport.update({
  id: '/convite',
  path: '/convite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConversarRoute = AuthenticatedConversarRouteImport.update({
  id: '/conversar',
  path: '/conversar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiarioRoute = AuthenticatedDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHojeRoute = AuthenticatedHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemediosRoute = AuthenticatedRemediosRouteImport.update({
  id: '/remedios',
  path: '/remedios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/convidado': typeof ConvidadoRoute
  '/convidado-diario': typeof ConvidadoDiarioRoute
  '/convidado-medicamentos': typeof ConvidadoMedicamentosRoute
  '/convidado-notificacoes': typeof ConvidadoNotificacoesRoute
  '/convite': typeof ConviteRoute
  '/conversar': typeof AuthenticatedConversarRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/remedios': typeof AuthenticatedRemediosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/convidado': typeof ConvidadoRoute
  '/convidado-diario': typeof ConvidadoDiarioRoute
  '/convidado-medicamentos': typeof ConvidadoMedicamentosRoute
  '/convidado-notificacoes': typeof ConvidadoNotificacoesRoute
  '/convite': typeof ConviteRoute
  '/conversar': typeof AuthenticatedConversarRoute
  '/diario': typeof AuthenticatedDiarioRoute
  '/hoje': typeof AuthenticatedHojeRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/remedios': typeof AuthenticatedRemediosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/convidado': typeof ConvidadoRoute
  '/convidado-diario': typeof ConvidadoDiarioRoute
  '/convidado-medicamentos': typeof ConvidadoMedicamentosRoute
  '/convidado-notificacoes': typeof ConvidadoNotificacoesRoute
  '/convite': typeof ConviteRoute
  '/_authenticated/conversar': typeof AuthenticatedConversarRoute
  '/_authenticated/diario': typeof AuthenticatedDiarioRoute
  '/_authenticated/hoje': typeof AuthenticatedHojeRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/remedios': typeof AuthenticatedRemediosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/convidado'
    | '/convidado-diario'
    | '/convidado-medicamentos'
    | '/convidado-notificacoes'
    | '/convite'
    | '/conversar'
    | '/diario'
    | '/hoje'
    | '/perfil'
    | '/remedios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/convidado'
    | '/convidado-diario'
    | '/convidado-medicamentos'
    | '/convidado-notificacoes'
    | '/convite'
    | '/conversar'
    | '/diario'
    | '/hoje'
    | '/perfil'
    | '/remedios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/convidado'
    | '/convidado-diario'
    | '/convidado-medicamentos'
    | '/convidado-notificacoes'
    | '/convite'
    | '/_authenticated/conversar'
    | '/_authenticated/diario'
    | '/_authenticated/hoje'
    | '/_authenticated/perfil'
    | '/_authenticated/remedios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConvidadoRoute: typeof ConvidadoRoute
  ConvidadoDiarioRoute: typeof ConvidadoDiarioRoute
  ConvidadoMedicamentosRoute: typeof ConvidadoMedicamentosRoute
  ConvidadoNotificacoesRoute: typeof ConvidadoNotificacoesRoute
  ConviteRoute: typeof ConviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convidado': {
      id: '/convidado'
      path: '/convidado'
      fullPath: '/convidado'
      preLoaderRoute: typeof ConvidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convidado-diario': {
      id: '/convidado-diario'
      path: '/convidado-diario'
      fullPath: '/convidado-diario'
      preLoaderRoute: typeof ConvidadoDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convidado-medicamentos': {
      id: '/convidado-medicamentos'
      path: '/convidado-medicamentos'
      fullPath: '/convidado-medicamentos'
      preLoaderRoute: typeof ConvidadoMedicamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convidado-notificacoes': {
      id: '/convidado-notificacoes'
      path: '/convidado-notificacoes'
      fullPath: '/convidado-notificacoes'
      preLoaderRoute: typeof ConvidadoNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite': {
      id: '/convite'
      path: '/convite'
      fullPath: '/convite'
      preLoaderRoute: typeof ConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/conversar': {
      id: '/_authenticated/conversar'
      path: '/conversar'
      fullPath: '/conversar'
      preLoaderRoute: typeof AuthenticatedConversarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diario': {
      id: '/_authenticated/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AuthenticatedDiarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hoje': {
      id: '/_authenticated/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof AuthenticatedHojeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/remedios': {
      id: '/_authenticated/remedios'
      path: '/remedios'
      fullPath: '/remedios'
      preLoaderRoute: typeof AuthenticatedRemediosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConversarRoute: typeof AuthenticatedConversarRoute
  AuthenticatedDiarioRoute: typeof AuthenticatedDiarioRoute
  AuthenticatedHojeRoute: typeof AuthenticatedHojeRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRemediosRoute: typeof AuthenticatedRemediosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConversarRoute: AuthenticatedConversarRoute,
  AuthenticatedDiarioRoute: AuthenticatedDiarioRoute,
  AuthenticatedHojeRoute: AuthenticatedHojeRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRemediosRoute: AuthenticatedRemediosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConvidadoRoute: ConvidadoRoute,
  ConvidadoDiarioRoute: ConvidadoDiarioRoute,
  ConvidadoMedicamentosRoute: ConvidadoMedicamentosRoute,
  ConvidadoNotificacoesRoute: ConvidadoNotificacoesRoute,
  ConviteRoute: ConviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
